# Generated by Django 5.1.5 on 2025-01-30 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vps',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='Uniq ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('cpu_cores', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(1)], verbose_name='Count cpu cores')),
                ('ram', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(1)], verbose_name='Count ram')),
                ('storage', models.SmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(1024), django.core.validators.MinValueValidator(15)], verbose_name='Count storage in Gb')),
                ('ip_address_private', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Private ip')),
                ('ip_address_public', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True, verbose_name='Public ip if is')),
                ('mac_address', models.CharField(max_length=48, null=True, unique=True, verbose_name='Mac address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time create')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time update')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User owner')),
            ],
            options={
                'verbose_name': 'VPS',
                'verbose_name_plural': 'VPS',
            },
        ),
    ]
