# Generated by Django 5.1.5 on 2025-02-10 20:58

import servers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='mac_address',
            field=models.CharField(default=servers.utils.generate_random_mac_address, max_length=48, null=True, unique=True, verbose_name='Mac address'),
        ),
    ]
